#!/bin/sh
#
# chkconfig: - 20 80
# description: ganglia-alert startup script
#
ganglia_alert=/usr/sbin/ganglia-alert

. /etc/rc.d/init.d/functions

test -f /etc/sysconfig/ganglia-alert && . /etc/sysconfig/ganglia-alert

export RRDCACHED_ADDRESS

start() {
    [ -x $ganglia_alert ] || exit 5
    [ -f /etc/ganglia/ganglia-alert.conf ] || exit 6
    echo -n "Starting ganglia-alert: "
    daemon $ganglia_alert -d
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/ganglia-alert
    return $RETVAL
}

stop() {
    echo -n "Shutting down ganglia-alert: "
    killproc $ganglia_alert
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/ganglia-alert
    return $RETVAL
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status $ganglia_alert
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

usage() {
    echo "Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
}

case "$1" in
    start)
	rh_status_q && exit 0
	$1
	;;
    stop)
	rh_status_q || exit 1
	$1
	;;
    restart)
	$1
	;;
    reload)
	rh_status_q || exit 7
	$1
	;;
    force-reload)
	force_reload
	;;
    status)
	rh_status
	;;
    condrestart|try-restart)
	rh_status_q || exit 0
	restart
	;;
    usage)
	$1
	;;
    *)
	usage
	exit 2
esac
exit $?
